name: Deploy Flutter Web to GitHub Pages 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo 
        uses: actions/checkout@v3 

      - name: Setup Flutter
        uses: subosito/flutter-action@v2 
        with:
          channel: 'stable'

      - name: Install dependencies 
        run: flutter pub get 

      - name: Build web 
        run: flutter build web --release 

      - name: Setup git 
        run: | 
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Debug GITHUB_TOKEN 
        run: echo "Token Length: ${GITHUB_TOKEN::4}****"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true